---
# tasks file for initconfig
- name: Update apt cache
  become: true
  apt:
    upgrade: true
    update_cache: yes
    cache_valid_time: 36000

- name: Install required software
  apt:
    state: present
    name: ['python-dev', 'python-mysqldb', 'libmysqlclient-dev', 'python-setuptools', 'python-pip']

- name: Check if pip installed
  command: "pip --version"

- name: install dependency
  command: "pip install mysql-connector-python"

