---
# tasks file for master
- hostname: 
    name: "master199.openshift.local"
  register: hostname_changed

- name: reboot node master
  shell: sudo reboot
  async: 1
  poll: 0
  when: hostname_changed is changed

- name: Wait for the reboot to complete if there was a change.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: hostname_changed is changed
  

- name: install the latest version of dnsmasq
  yum:
    name: dnsmasq
    state: latest



- name: create file openshift.conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0777
  with_items:
    - { src: 'roles/master/templates/openshift.conf.j2', dest: '/etc/dnsmasq.d/openshift.conf' }


- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"


- name: Edit listen_address in  /etc/dnsmasq.conf 
  lineinfile:
    path: /etc/dnsmasq.conf
    regexp: '^listen_address='
    insertafter: '^#listen-address='
    line: listen-address={{ master_address  }}


- name: Edit server in /etc/dnsmasq.conf
  lineinfile:
    path: /etc/dnsmasq.conf
    regexp: '^server='
    insertafter: '^#server='
    line: server=8.8.8.8


- name: Edit server in /etc/dnsmasq.conf
  lineinfile:
    path: /etc/resolv.conf
    regexp: '^nameserver '
    insertafter: '^nameserver '
    line: nameserver {{ master_address  }}

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"

